# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
# FROM REST_INFO AS R1
# WHERE FAVORITES IN (SELECT MAX(FAVORITES) FROM REST_INFO AS R2 GROUP BY FOOD_TYPE WHERE R1.REST_ID = R2.REST_ID)
# ORDER BY FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FOOD_TYPE IN (
    SELECT FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    HAVING FAVORITES = MAX(FAVORITES)
)
ORDER BY FOOD_TYPE DESC;

